export const siteConfig = {
  name: "DVR Global Careers",
  shortName: "DVR",
  url: "https://dvrglobalcareers.example.com",
  description:
    "DVR Global Career provides industry-focused Oil & Gas, Warehouse Management, Shipbuilding, and Industrial Skills Training with dedicated placement support for India, GCC, and global careers.",
  phone: "+91 8095728432",
  whatsapp: "918095728432",
  email: "dvrglobalcareers@gmail.com",
  address: "DVR INSTITUTE, No:30 2nd floor, UNIQCON PLAZA, Kamaraj Salai, Karaikal, Puducherry State - 609602",
  city: "Karaikal",
  region: "Puducherry",
  postalCode: "609602",
  logo: "/dvr-logo-official.png",
  logoSmall: "/dvr-logo-official.png",
};

export const navLinks = [
  { label: "About", href: "/about" },
  // { label: "Courses", href: "/courses" },
  { label: "Categories", href: "/categories" },
  { label: "Placements", href: "/placements" },
  { label: "Gallery", href: "/gallery" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Contact", href: "/contact" },
];

export const imageAssets = {
  hero: "/home-images/dvr-front-page-sunset-hero.png",
  heroMobile: "/home-images/mobile-hero-refinery.png",
  classroom: "/home-images/practical-career-training.jpg",
  ship: "/home-images/shipbuilding-careers.jpg",
  safety: "/home-images/fire-safety-careers.jpg",
  logistics: "/home-images/warehouse-logistics.jpg",
  training: "/home-images/offshore-onshore-industry-training.jpg",
  offshoreTraining: "/home-images/offshore-training.jpg",
  onshoreTraining: "/home-images/onshore-training.jpg",
  warehouseLogistics: "/home-images/warehouse-logistics.jpg",
  warehouseOperationsInventoryManagement: "/home-images/warehouse-operations-inventory-management.png",
  warehouseMaterialHandlingLogistics: "/home-images/warehouse-material-handling-logistics.png",
  warehouseStockLogisticsCoordination: "/home-images/warehouse-stock-logistics-coordination.png",
  logisticsSupplyChainManagement: "/home-images/logistics-supply-chain-management.png",
  shipbuildingCareers: "/home-images/shipbuilding-careers.jpg",
  shipConstructionFabrication: "/home-images/ship-construction-fabrication.png",
  shipyardConstructionOperations: "/home-images/shipyard-construction-operations.png",
  marineShipbuildingMaintenance: "/home-images/marine-shipbuilding-maintenance.png",
  shipyardFabricationPipeFitting: "/home-images/shipyard-fabrication-pipe-fitting.png",
  fireSafetyCareers: "/home-images/fire-safety-careers.jpg",
  firePreventionIndustrialSafety: "/home-images/fire-prevention-industrial-safety.png",
  safetyManagementEmergencyResponse: "/home-images/safety-management-emergency-response.png",
  fireSafetyHazardAccidentPrevention: "/home-images/fire-safety-hazard-accident-prevention.png",
  workplaceSafetyHazardControl: "/home-images/workplace-safety-hazard-control.png",
  practicalCareerTraining: "/home-images/practical-career-training.jpg",
  riggingSlinging: "/home-images/rigging-slinging.jpg",
  banksmanTraining: "/home-images/banksman-training.jpg",
  oilGasFieldTraining: "/home-images/oil-gas-field-training.jpg",
  roustaboutTraining: "/home-images/roustabout-training.jpg",
  offshoreOnshoreIndustryTraining: "/home-images/offshore-onshore-industry-training.jpg",
  bosiet: "/home-images/bosiet.jpg",
  huet: "/home-images/huet.jpg",
  mechanicalFitter: "/home-images/mechanical-fitter.jpg",
  pipeFitter: "/home-images/pipe-fitter.jpg",
  generalFitter: "/home-images/general-fitter.jpg",
  instrumentTechnician: "/home-images/instrument-technician.jpg",
  electricalTechnician: "/home-images/electrical-technician.jpg",
  mechanicalTechnician: "/home-images/mechanical-technician.jpg",
  firewatchHolewatch: "/home-images/firewatch-holewatch.jpg",
  permitReceiverJobPerformerLeadWorker: "/home-images/permit-receiver-job-performer-lead-worker.jpg",
};
